title: Jussi Hallila
description: Personal ramblings and tech babble
author: Jussi Hallila
logo: /static/img/avatar.jpg
github: https://github.com/Xantier
about: Talk is cheap, show me the code

baseurl: "https://jussi.hallila.com"
url: "https://jussi.hallila.com"

disqus_shortname: jussi-hallila-com
google_analytics: UA-42218347-5

share:
  twitter_username: Xantier
  fb_appid: 000000000000

collections:
    books:
      output: true
      permalink: /books/:path/

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
gems: [jekyll-paginate, jekyll-gist]

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
