title: Jussi Hallila
description: Truefullstack
author: Jussi Hallila
logo: /static/img/avatar.jpg
github: https://github.com/Xantier
about: Talk is cheap, show me the code

baseurl: "http://jussi.hallila.com"
url: "http://jussi.hallila.com"

disqus_shortname: xantier
google_analytics: UA-42218347-5

share:
  twitter_username: \Xantier
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
